# Generated by Django 2.2.4 on 2019-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumeprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_mail', models.CharField(max_length=200)),
                ('resume_file', models.FileField(upload_to='documents/%d%m%Y/')),
                ('resume_date', models.DateTimeField(auto_now_add=True)),
                ('resume_status', models.CharField(choices=[('Applied', 'Applied'), ('Viewed', 'Viewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=15)),
            ],
            options={
                'db_table': 'resumeprofile',
            },
        ),
    ]
